### PR TITLE
trying to tell where conflicts lie

### PR DESCRIPTION
**Pull request by fchapoton**
it's not so easy to tell which branch the conflicts comes from. Maybe one could use the information in ".git/MERGE_HEAD"

### CODE REVIEW

**Comment by vbraun** [comment]
The way to do it is: 
* Abort the conflicting merge attempt
* Detach head
* Go back in history (first parents) until the merge succeeds
* Now you know which ticket introduced the merge
* Switch back to the original branch

**Comment by fchapoton** [comment]
Maybe my simple-minded proposal (if it works) would at least allow you to tell people in which files there is a conflict ?

**Comment by fchapoton** [comment]
Maybe my not-so-smart little change would still be useful ?

**Comment by embray** [comment]
I think it's better than nothing, yeah.

**Comment by embray** [comment]
Another idea would be to simply produce the git log since the last commit on the `develop` branch, which would provide a list of exactly which branches have been merged (if not necessarily the exact one that has the merge conflict).

**Pull request merged**
